#!/usr/bin/env python3

import requests
import json
import plotly.graph_objects as go
import pandas as pd

serieid = input('Please enter a serie ID\n') # APU0000702212
response = requests.get(f'http://api.bls.gov/publicAPI/v2/timeseries/data/{serieid}.json?startyear=2009&endyear=2020')
response.raise_for_status()

df = response.json()['Results']['series'][0]['data']
df.reverse()
for el in df:
    el['Date'] = f"{el['periodName']} {el['year']}"
df = pd.DataFrame(df)

fig = go.Figure()
fig.add_trace(go.Scatter(
                x=df['Date'],
                y=df['value'],
                line_color='deepskyblue',
                opacity=1.0))
fig.show()