#!/usr/bin/env python3

import plotly.graph_objects as go

p = input('Please enter a product\n')
q = input('Please enter the maximum quantity\n')

try:
    q = int(q)
    assert(q > 0)
except ValueError:
    print('The quantity value you have entered is not a number !')
    exit(1)
except AssertionError:
    print('The quantity value you have entered need to be non-null and positive !')
    exit(1)

data = {'utility': [], f'{p}': []}

for x in range(0, q):
    h = input(f'For {x+1} {p.lower()} what added happiness do you get?\n')
    try:
        h = int(h)
        data['utility'].append(h)
        data[f'{p}'].append(x+1)
    except ValueError:
        print('The happiness value you have entered is not a number !')
        exit(1)

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=data[f'{p}'],
    y=data['utility'],
    line_color='deepskyblue'))

fig.update_layout(
    title=f"{p} marginal utility",
    xaxis_title=f"Number of {p.lower()}",
    yaxis_title=f"Utility of {p.lower()}"
    )

fig.show()