#!/usr/bin/env python3

import plotly.express as px
import pandas as pd
from random import randrange

df1 = pd.read_csv("world_bank_gdp.csv", skiprows=4)
df2 = pd.read_csv("world_bank_tariff.csv", skiprows=4)

df = pd.merge(df1, df2, on=['Country Name','Country Code'])

df = df[pd.notna(df['2017_x'])]
df = df[pd.notna(df['2017_y'])]

df = df.rename(columns={"2017_x": "GDP", "2017_y": "Tariff"})
df = df.sample(n=10)

fig = px.scatter(df, x='GDP', y='Tariff', text=df['Country Name'])
fig.update_traces(textposition='top center')
fig.show()