#!/usr/bin/env python3

import plotly.graph_objects as go
import pandas as pd

df = pd.read_csv("data.csv")

fig = go.Figure()
fig.add_trace(go.Scatter(
                x=df['price'],
                y=df[' quanity demanded'],
                name='Quantity demanded',
                line_color='deepskyblue',
                opacity=0.8))

fig.add_trace(go.Scatter(
                x=df['price'],
                y=df[' quantity supplied'],
                name='Quantity supplied',
                line_color='dimgray',
                opacity=0.8))

# Use date string to set xaxis range
fig.update_layout(xaxis_range=['2016-07-01','2016-12-31'],
                  title_text="Manually Set Date Range")
fig.show()